### PR TITLE
Investigations

### PR DESCRIPTION
**Pull request by T-Nicholls**
The conversion limits are about 70% of the way there, I'll probably finish them from home next week as it bothers me to leave them unfinished.

### CODE REVIEW

**Comment by willrogers** [comment]
In the very reasonable event that you do not decide to do this, can you tell me what you mean by 'about 70%'?

**Comment by T-Nicholls** [comment]
All the plumbing to get the limits onto the unit convs is done, and the `convert` method does check that the results are within the bounds. However, the `_raw_phys_to_eng` methods of the pchip and poly unit convs still apply their old checks to the results, according to the csv values, not the limits. So a value outside the bounds but inside the limits would be discarded, thus the `convert` method's check that the result is inside the limits is essentially useless as the conversion bounds are always smaller than the limits.
I think the fix for this is to:
- remove all checks from raw methods and just return a numpy array of all results.
- have all checking occur inside `convert`, rather than trying to split it across methods.
- if we have two results inside limits but only on is inside bounds, then use that one; otherwise, raise an error.
if you agree that this is the way to go about it then I'm happy to do it as it should be reasonably quick, I suspect that updating the tests will be the longest bit.

**Comment by willrogers** [comment]
Yes, I think that is correct. You should feel entirely free not to do this!

I also realised that `set_post_phys_to_eng()` etc. wasn't the right thing to do, we should have just made the attributes public. I will change this at some point.

**Comment by T-Nicholls** [comment]
It didn't integrate as smoothly as I hoped.
- I put everything in the `convert` method, as discussed, though I think it can be done more cleanly and needs more descriptive variable names, but it works.
- I removed `eng_to_phys` and `phys_to_eng` and put their functionality in `convert` too.
- I will update the tests on Wednesday/Thursday but thought I'd push what I've done so far to get any feedback.

**Comment by willrogers** [comment]
There's a couple of comments I'd make:

* `id` isn't really related to the functionality of `UnitConv`, it's just used to help debugging when something goes wrong. I'd be more inclined to set it as an attribute and use it in error messages if it's there than to require it every time you create such an object
* I'm not sure why you removed `eng_to_phys()` and phys_to_eng()` as I think they could contain the new functionality. Shorter methods are usually better than longer ones.

You absolutely shouldn't feel the need to continue working on this, I can pick it up.

**Comment by T-Nicholls** [comment]
I agree id shouldn’t be required and probably should be a private attribute anyway, just for use in error messages.
I felt the eng_to_phys and phys_to_eng methods were a bit redundant as we mostly used the convert method internally in pytac so I moved them to convert as it was only two lines; but I agree we could move all the new functionality there instead of convert and that would make more sense.

**Pull request merged**
